#
# Copyright 2019, Intel Corporation
#
# 'recipe' for Docker to build an RPM
#

# Pull base image
FROM suse/sles:12.3
MAINTAINER Brian J. Murrell <brian.murrell@intel.com>

# use same UID as host and default value of 1000 if not specified
ARG UID=1000

# Add build user (to keep rpmbuild happy)
ENV USER build
ENV PASSWD build
RUN useradd -u $UID -ms /bin/bash $USER
RUN groupadd -g $UID $USER
RUN echo "$USER:$PASSWD" | chpasswd

# Install basic tools
RUN zypper --non-interactive update
# basic building
RUN zypper --non-interactive install make rpm-build curl createrepo git    \
                                     lsb-release autoconf automake libtool \
                                     ca-certificates-mozilla
# spdk
RUN zypper --non-interactive ar --gpgcheck-allow-unsigned -f https://build.hpdd.intel.com/job/daos-stack/job/dpdk/job/master/lastSuccessfulBuild/artifact/artifacts/sles12.3/ dpdk; \
    zypper --non-interactive ar --gpgcheck-allow-unsigned -f https://build.hpdd.intel.com/job/daos-stack/job/fio/job/master/lastSuccessfulBuild/artifact/artifacts/sles12.3/ fio;   \
    zypper --non-interactive --gpg-auto-import-keys ref dpdk fio
RUN zypper --non-interactive install dpdk-devel fio-src libiscsi-devel       \
                                     cunit-devel libnuma-devel openssl-devel \
                                     libaio-devel libuuid-devel              \
                                     rdma-core-devel gcc-c++

# force an upgrade to get any newly built RPMs
ARG CACHEBUST=1
RUN zypper --non-interactive up
